version: '3'

services:
  db:
    image: postgres:12.7
    environment:
      POSTGRES_USER: user_lmad
      POSTGRES_PASSWORD: user_lmad
      POSTGRES_DB: flight_db
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
